name: Hello World Workflow

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run Hello World Action
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Mona the Octocat"
