version: 2.1

# orbs:
#   node: circleci/node@x.y

commands:
  install-act:
    parameters:
      version:
        type: string
        default: "latest"
      debug:
        type: boolean
        default: false
      bin-dir:
        type: string
        default: "/home/circleci/bin"
    steps:
      - run:
          name: "Installing Act << parameters.version >>"
          command: |
            # Set the bin-dir and debug flags based on the parameters
            BIN_DIR_FLAG=""
            DEBUG_FLAG=""

            # Check if a custom bin directory is set
            if [[ "<< parameters.bin-dir >>" != "./bin" ]]; then
              BIN_DIR_FLAG="-b << parameters.bin-dir >>"
            fi

            # Enable debug logging if the debug parameter is true
            if [[ "<< parameters.debug >>" == "true" ]]; then
              DEBUG_FLAG="-d"
            fi

            # Install Act with the specified version, bin-dir, and debug options
            curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- $BIN_DIR_FLAG $DEBUG_FLAG << parameters.version >>

  act:
    parameters:
      uses:
        type: string
      with:
        type: string
      env:
        type: string
    steps:
      - run:
          name: Running << parameters.uses >>
          command: |
            echo "test"

jobs:
  test:
    machine:
      image: ubuntu-2404:current
    steps:
      - checkout
      - install-act
      - run: act -W hello-world.yml


workflows:
  main:
    jobs:
      - test